openapi: 3.0.1
info:
  title: API Adhérents
  description: Description de l'API Adhérents
  contact:
    email: manu.chenais@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://adherents.jalle-astro.fr/v1
- url: http://adherents.jalle-astro.fr/v1
tags:
- name: adherent
  description: gestion des adhérents
  externalDocs:
    description: Pour plus de détail
    url: http://plusdedétail.ht
paths:
  /adherent:
    put:
      tags:
      - adherent
      summary: Mise à jour de l'adherent
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - name: username
        in: path
        description: name that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Adherent'
        required: true
      responses:
        400:
          description: Invalid user supplied
          content: {}
        404:
          description: User not found
          content: {}
    post:
      tags:
      - adherent
      summary: Ajouter un adhérent
      operationId: ajoutAdherent
      requestBody:
        description: Besoin de l'objet adhérent pour ajouter un adhérent
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Adherent'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      security:
      - petstore_auth:
        - adh:write
        - adh:read
      - bearerAuth: []
  /adherent/{idAdh}:
    get:
      tags:
      - adherent
      summary: rechercher adherent par id
      operationId: getAdherent
      parameters:
      - name: idAdh
        in: path
        description: Id de l'adhérent à récupérer
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Operation réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adherent'
        400:
          description: ID adherent invalide
          content: {}
        404:
          description: adherent non trouvé
          content: {}
      security:
      - petstore_auth:
        - adh:read
      - bearerAuth: []
    delete:
      tags:
      - adherent
      summary: Supression de l'adherent par id
      operationId: deleteUser
      parameters:
      - name: idAdh
        in: path
        description: Id de l'adhérent à récupérer
        required: true
        schema:
          type: integer
      responses:
        400:
          description: ID adherent invalide
          content: {}
        404:
          description: adherent non trouvé
          content: {}
      security:
      - petstore_auth:
        - adh:del
      - bearerAuth: []
components:
  schemas:
    Adherent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        civilite:
          type: string
          description: civilite de l'adhenrent
          enum:
          - Monsieur
          - Madame
        nom:
          maxLength: 20
          minLength: 3
          type: string
        prenom:
          maxLength: 20
          minLength: 3
          type: string
        adresse1:
          maxLength: 37
          minLength: 3
          type: string
        adresse2:
          maxLength: 37
          minLength: 3
          type: string
        codePostal:
          maxLength: 5
          minLength: 5
          type: string
        telMaison:
          maxLength: 10
          minLength: 10
          type: string
        telTravail:
          maxLength: 10
          minLength: 10
          type: string
        telPortail:
          maxLength: 10
          minLength: 10
          type: string
        privilege:
          type: string
          description: privilege
          enum:
          - Adherent
          - Conseil administration
          - Bureau
          - Admin
        email:
          maxLength: 40
          minLength: 5
          type: string
        profession:
          maxLength: 50
          minLength: 5
          type: string
        dateNaissance:
          type: string
          format: date-time
        telescope:
          type: boolean
        lunette:
          type: boolean
        jumelles:
          type: boolean
        modelInstrument:
          type: string
        commentaire:
          maxLength: 100
          minLength: 2
          type: string
      xml:
        name: Order
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://adherents.jalle-astro.fr/token/
          scopes:
            adh:write: modification d'un adherents
            adh:read: lecture d'un adhérent
            adh:del: suppression d'un adherent
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      name: api_key
      in: header
