openapi: 3.0.1
info:
  title: API Adhérents
  description: Description de l'API Adhérents
  contact:
    email: manu.chenais@gmail.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
servers:
  - url: 'https://api.jalle-astro.fr/resource-adherents/'
tags:
  - name: adherent
    description: gestion des adhérents
  - name: listing adherent
    description: listing des adhérents
  - name: adhesion
    description: gestion des adhesions
  - name: Manifestation
    description: Gestion de la participation d'un adherent à une manifestion
  - name: Communication
    description: Gestion de communication d'un adherent
  - name: liens adherents
    description: Gestion des liens entre adherents
paths:
  /adherent:
    post:
      tags:
        - adherent
      summary: Ajouter un adhérent
      operationId: ajoutAdherent
      security:
        - oAuth:
            - ress-adherent-admin
    get:
      tags:
        - adherent
      summary: rechercher adherent via son mail
      operationId: getAdherentByMail
      security:
        - oAuth:
            - ress-adherent-read
  '/adherent/{idadh}':
    get:
      tags:
        - adherent
      summary: recuperer adherent
      operationId: getAdherent
      security:
        - oAuth:
            - ress-adherent-read
    delete:
      tags:
        - adherent
      summary: Supression de l'adherent
      operationId: deleteUser
      security:
        - oAuth:
            - ress-adherent-del
    put:
      tags:
        - adherent
      summary: Mise à jour de l'adherent
      description: Mise à jour de l'adherent
      operationId: updateUser
      security:
        - oAuth:
            - ress-adherent-write
  '/adherent/{idadh}/liens':
    get:
      tags:
        - liens adherents
      summary: recuperer  les liens d'un adherent
      operationId: getLienAdherent
      security:
        - oAuth:
            - ress-adherent-read
  '/adherent/{idadh}/lien/{idAdhLien}':                
    delete:
      tags:
        - liens adherents
      summary: Supprimer un lien adherent
      operationId: deleteLienAdherent
      security:
        - oAuth:
            - ress-adherent-del
    post:
      tags:
        - liens adherents
      summary: Ajouter un lien entre 2 adherents
      operationId: ajoutLienAdherent
      security:
        - oAuth:
            - ress-adhesion-write
  '/adherent/{idadh}/photo':              
    put:
      tags:
        - adherent
      summary: Mise à jour de la photo de l'adhérent
      description: Mise à jour de la photo de l'adhérent
      operationId: updateUserPhoto
      security:
        - oAuth:
            - ress-adherent-write
  '/adherent/{idadh}/adhesion':
    post:
      tags:
        - adhesion
      summary: Ajouter une adhesions pour un adherent
      operationId: ajoutAdhesionAdherent
      security:
        - oAuth:
            - ress-adhesion-write
  '/adherent/{idadh}/adhesions':
    get:
      tags:
        - adhesion
      summary: rechercher la liste des adhésions pour un adherent
      operationId: getListeAdhesionsAdherent
      security:
        - oAuth:
            - ress-adhesion-read
  '/adherent/{idadh}/adhesion/{idAdhesion}' :
    get:
      tags:
        - adhesion
      summary: rechercher une adhésion pour un adherent
      operationId: getAdhesionAdherent
      security:
        - oAuth:
            - ress-adhesion-read
    delete:
      tags:
        - adhesion
      summary: Supression d'une adhesion pour cet adherent
      operationId: deleteAdhesionAdherent
      security:
        - oAuth:
            - ress-adhesion-del
    put:
      tags:
        - adhesion
      summary: Mise à jour d'une adhesion pour cet adherent
      description: Mise à jour d'une adhesion pour cet adherent
      operationId: updateAdhesionAdherent
      security:
        - oAuth:
            - ress-adhesion-write
  '/adherent/liste':
    get:
      tags:
        - listing adherent
      summary: Récupérer l'ensemble des adhérents
      operationId: getListeAdherents
      security:
        - oAuth:
            - ress-adherent-read
  '/adherent/listeSaison':
    get:
      tags:
        - listing adherent
      summary: Récupérer l'ensemble des adhérents de la saison
      operationId: getListeAdherentsSaison
      security:
        - oAuth:
            - ress-adherent-read
  '/adherent/{idadh}/manifestions':
    get:
      tags:
        - Manifestation
      summary: rechercher la liste des manifestations affectée au un adhérents
      operationId: getListeManifestationsAdherent
      security:
        - oAuth:
            - ress-manifestation-read
  '/adherent/{idadh}/manifestion/{idManifestation}':
    get:
      tags:
        - Manifestation
      summary: rechercher le d'étail d'une  manifestations affectée au un adhérent
      operationId: getManifestationsAdherent
      security:
        - oAuth:
            - ress-manifestation-read
    post:
      tags:
        - Manifestation
      summary: Ajouter la participation à une manifestation pour un adherent
      operationId: ajoutManifestationAdherent
      security:
        - oAuth:
            - ress-manifestation-write
    delete:
      tags:
        - Manifestation
      summary: Supression d'une manifestation pour un adherent
      operationId: deleteManifestationAdherent
      security:
        - oAuth:
            - ress-manifestation-del
    put:
      tags:
        - Manifestation
      summary: Mise à jour d'une manifestation pour un adherent
      description: Mise à jour d'une manifestation pour un adherent
      operationId: updateManifestationAdherent
      security:
        - oAuth:
            - ress-manifestation-write
  '/adherent/{idadh}/communications':
    get:
      tags:
        - Communication
      summary: rechercher la liste de communications que le client a recu
      operationId: getListeCommunicationAdhrent
      security:
        - oAuth:
            - ress-communication-read
components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: 'This API uses OAuth 2 with the implicit grant flow. [More info]'
      flows:
        clientCredentials:
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources autorisation
        authorizationCode:
          authorizationUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/authorize'
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources adherent
            ress-adherent-read: droit de lecteur sur les ressoruces adherent
            ress-adherent-write: droit d'écriture sur les ressoruces adherent
            ress-adherent-del: droit de suppression sur les ressoruces adherent
            ress-adhesion-admin: droit administration sur les ressources adhesion
            ress-adhesion-read: droit de lecteur sur les ressoruces adhesion
            ress-adhesion-write: droit d'écriture sur les ressoruces adhesion
            ress-adhesion-del: droit de suppression sur les adherent adhesion
            ress-manifestation-admin: droit administration sur les ressources manifestation
            ress-manifestation-read: droit de lecteur sur les ressoruces manifestation
            ress-manifestation-write: droit d'écriture sur les ressoruces manifestation
            ress-manifestation-del: droit de suppression sur les adherent manifestation
            ress-communication-read: droit de lecture des communication envoyé aux adherents
        password:
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources adherent
            ress-adherent-read: droit de lecteur sur les ressoruces adherent
            ress-adherent-write: droit d'écriture sur les ressoruces adherent
            ress-adherent-del: droit de suppression sur les adherent autorisation
            ress-adhesion-admin: droit administration sur les ressources adhesion
            ress-adhesion-read: droit de lecteur sur les ressoruces adhesion
            ress-adhesion-write: droit d'écriture sur les ressoruces adhesion
            ress-adhesion-del: droit de suppression sur les adherent adhesion
            ress-manifestation-admin: droit administration sur les ressources manifestation
            ress-manifestation-read: droit de lecteur sur les ressoruces manifestation
            ress-manifestation-write: droit d'écriture sur les ressoruces manifestation
            ress-manifestation-del: droit de suppression sur les adherent manifestation
            ress-communication-read: droit de lecture des communication envoyé aux adherents
