openapi: 3.0.1
info:
  title: API utilitaires
  description: Description de l'API utilitaire
  contact:
    email: manu.chenais@gmail.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
servers:
  - url: 'https://api.jalle-astro.fr/resource-utilitaire/'
tags:
  - name: Agenda
    description: gestion de l'agendas
  - name: Documentation
    description: gestion de la documentation de l'association
  - name: Diffusion mail
    description: gestion de la diffusion des mails
  - name: Saison
    description: Gestion des saisons
paths:
  /agenda/evenement:
    post:
      tags:
        - Agenda
      summary: Ajouter un évenement
      operationId: addEvenement
      security:
        - oAuth:
            - ress-utilitaire-agenda-add
  '/agenda/evenement/{idevenement}':
    get:
      tags:
        - Agenda
      summary: rechercher un evenement
      operationId: getEvenement
      security:
        - oAuth:
            - ress-utilitaire-agenda-read
    delete:
      tags:
        - Agenda
      summary: Supprimer un evenement
      operationId: deleteEvenement
      security:
        - oAuth:
            - ress-utilitaire-agenda-del
    put:
      tags:
        - Agenda
      summary: Mise à jour d'une evenement
      description: Mise à jour d'un evenement
      operationId: updateEvenement
      security:
        - oAuth:
            - ress-utilitaire-agenda-write
  '/agenda/evenement/{idevenement}/synthese':
    get:
      tags:
        - Agenda
      summary: rechercher la synthese des participations à un évènement
      operationId: getSyntheseEvenement
      security:
        - oAuth:
            - ress-utilitaire-agenda-read
  '/agenda/evenements':
    get:
      tags:
        - Agenda
      summary: rechercher la liste d'évenement
      operationId: getListeEvenements
      security:
        - oAuth:
            - ress-utilitaire-agenda-read
  '/agenda/synthese':
    get:
      tags:
        - Agenda
      summary: rechercher la synthèse des participations aux évènement
      operationId: getSyntheseEvenements
      security:
        - oAuth:
            - ress-utilitaire-agenda-read
  /saison/active:
    get:
      tags:
        - Saison
      summary: récupérer la saison courante
      operationId: getSaisonCourante
      security:
        - oAuth:
            - ress-utilitaire-saison-read
  /saison/{idSaison}/active:
    put:
      tags:
        - Saison
      summary: Mise à jour de la saison courante
      description: Mise à jour de la saison courante
      operationId: updateSaisonCourante
      security:
        - oAuth:
            - ress-utilitaire-saison-write
  /saison/liste:
    get:
      tags:
        - Saison
      summary: récupérer la liste des saisons
      operationId: getListeSaison
      security:
        - oAuth:
            - ress-utilitaire-saison-read
  /documents:
    get:
      tags:
        - Documentation
      summary: Rechercher une liste de document
      operationId: getDocuments
      security:
        - oAuth:
            - ress-utilitaire-documents-read
  /documents/arboresence:
    get:
      tags:
        - Documentation
      summary: Recupérer l'arboresence complet
      operationId: getArboresence
      security:
        - oAuth:
            - ress-utilitaire-documents-read
  /documents/dossier:
    post:
      tags:
        - Documentation
      summary: Ajouter un dossier
      operationId: addDossier
      security:
        - oAuth:
            - ress-utilitaire-dossier-add
  '/documents/dossier/{idDossier}':
    get:
      tags:
        - Documentation
      summary: Recupérer les informations d'un dossier
      operationId: getDossier
      security:
        - oAuth:
            - ress-utilitaire-dossier-read
    delete:
      tags:
        - Documentation
      summary: Supprimer un dossier (avec les sous fichier associé)
      operationId: delDossier
      security:
        - oAuth:
            - ress-utilitaire-dossier-del
    put:
      tags:
        - Documentation
      summary: Mise à jour d'un dossier
      operationId: majDossier
      security:
        - oAuth:
            - ress-utilitaire-dossier-add
  /documents/fichier:
    post:
      tags:
        - Documentation
      summary: Ajouter un fichier (sans le binaire)
      operationId: addFichier
      security:
        - oAuth:
            - ress-utilitaire-fichier-add
  '/documents/fichier/{idFichier}':
    post:
      tags:
        - Documentation
      summary: Ajouter fichier binaire
      operationId: addFichierBinaire
      security:
        - oAuth:
            - ress-utilitaire-fichier-add
    get:
      tags:
        - Documentation
      summary: Recupérer les informations d'un fichier
      operationId: getFichier
      security:
        - oAuth:
            - ress-utilitaire-fichier-read
    delete:
      tags:
        - Documentation
      summary: Supprimer un fichier 
      operationId: delFichier
      security:
        - oAuth:
            - ress-utilitaire-fichier-del
    put:
      tags:
        - Documentation
      summary: Mise à jour d'un fichier
      operationId: majFichier
      security:
        - oAuth:
            - ress-utilitaire-fichier-add
components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: 'This API uses OAuth 2 with the implicit grant flow. [More info]'
      flows:
        clientCredentials:
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources autorisation
        authorizationCode:
          authorizationUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/authorize'
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources adherent
        password:
          tokenUrl: 'https://api.jalle-astro.fr/authorization-server/oauth/token'
          scopes:
            ress-adherent-admin: droit administration sur les ressources adherent
