/*
 * Swagger mailjet
 * Swagger mailjet
 *
 * OpenAPI spec version: 1.0.0
 * Contact: manu.chenais@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.espaceadh.lib.mail.model.mailjet;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ListeMessages
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-15T20:39:15.462Z[GMT]")
public class ListeMessages {
  @SerializedName("Count")
  private Long count = null;

  @SerializedName("Data")
  private List<Message> data = null;

  @SerializedName("Total")
  private Long total = null;

  public ListeMessages count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Nombre de message
   * @return count
  **/
  @Schema(example = "1", description = "Nombre de message")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public ListeMessages data(List<Message> data) {
    this.data = data;
    return this;
  }

  public ListeMessages addDataItem(Message dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<Message>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<Message> getData() {
    return data;
  }

  public void setData(List<Message> data) {
    this.data = data;
  }

  public ListeMessages total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Nombre de message
   * @return total
  **/
  @Schema(example = "1", description = "Nombre de message")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListeMessages listeMessages = (ListeMessages) o;
    return Objects.equals(this.count, listeMessages.count) &&
        Objects.equals(this.data, listeMessages.data) &&
        Objects.equals(this.total, listeMessages.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, data, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListeMessages {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
